WiseSwitch/ViewModels/Entities/ProductLine/CreateProductLineViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WiseSwitch.ViewModels.Entities.ProductLine
{
    public class CreateProductLineViewModel : IInputViewModel
    {
        [Required(ErrorMessage = "A Name is required for the Product Line.")]
        public string Name { get; set; }


        [Display(Name = "Brand")]
        [Range(1, int.MaxValue, ErrorMessage = "The ID for the Brand is not valid.")]
        public int BrandId { get; set; }
    }
}

WiseSwitch/ViewModels/Entities/ProductLine/DisplayProductLineViewModel.cs
namespace WiseSwitch.ViewModels.Entities.ProductLine
{
    public class DisplayProductLineViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }


        public string BrandName { get; set; }


        public IEnumerable<string> ProductSeriesNames { get; set; }
    }
}

WiseSwitch/ViewModels/Entities/ProductLine/EditProductLineViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WiseSwitch.ViewModels.Entities.ProductLine
{
    public class EditProductLineViewModel : IInputViewModel
    {
        public int Id { get; set; }


        [Required(ErrorMessage = "A Name is required for the Product Line.")]
        public string Name { get; set; }


        [Display(Name = "Brand")]
        [Range(1, int.MaxValue, ErrorMessage = "The ID for the Brand is not valid.")]
        public int BrandId { get; set; }
    }
}

WiseSwitch/ViewModels/Entities/ProductLine/IndexRowProductLineViewModel.cs
namespace WiseSwitch.ViewModels.Entities.ProductLine
{
    public class IndexRowProductLineViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }


        public string BrandName { get; set; }
    }
}

WiseSwitch/Controllers/ProductLinesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WiseSwitch.Services.Api;
using WiseSwitch.Services.Data;
using WiseSwitch.Utils;
using WiseSwitch.ViewModels.Entities.ProductLine;

namespace WiseSwitch.Controllers
{
    [Authorize(Roles = "Admin,Technician")]
    public class ProductLinesController : AppController
    {
        private readonly DataService _dataService;

        protected override async Task GetInputCombos()
        {
            var getCombo = await _dataService.GetAsync<IEnumerable<SelectListItem>>(ApiUrls.GetBrandsCombo, null);
            if (getCombo.IsSuccess)
            {
                ViewBag.ComboBrands = getCombo.Result;
            }
            else throw new Exception("Could not get input combo from API.");
        }

        public ProductLinesController(DataService dataService)
        {
            _dataService = dataService;
        }


        // GET: ProductLines
        public async Task<IActionResult> Index()
        {
            var getAll = await _dataService.GetAsync<IEnumerable<IndexRowProductLineViewModel>>(ApiUrls.GetAllProductLines);

            return ManageGetDataResponse<IEnumerable<IndexRowProductLineViewModel>>(getAll);
        }


        // GET: ProductLines/5
        public async Task<IActionResult> Details(int id)
        {
            // Check given ID is valid.
            if (id < 1) return IdIsNotValid(EntityNames.ProductLine);

            // Try get model.
            var getModel = await _dataService.GetAsync<DisplayProductLineViewModel>(ApiUrls.GetProductLineDisplay, id);

            // Resolve response.
            return ManageGetDataResponse<DisplayProductLineViewModel>(getModel);
        }


        // GET: ProductLines/Create
        public async Task<IActionResult> Create(int brandId)
        {
            var model = brandId < 1 ? null : new CreateProductLineViewModel { BrandId = brandId };

            return await ViewInput(model);
        }

        // POST: ProductLines/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateProductLineViewModel model)
        {
            if (!ModelState.IsValid)
                return await ModelStateInvalid(model, EntityNames.ProductLine);

            // Try create ProductLine.
            var create = await _dataService.CreateAsync(ApiUrls.CreateProductLine, model);

            // Resolve response.
            return ManageInputResponse(create);
        }

        // GET: ProductLines/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            // Check given ID is valid.
            if (id < 1) return IdIsNotValid(EntityNames.ProductLine);

            // Try to get model.
            var getModel = await _dataService.GetAsync<EditProductLineViewModel>(ApiUrls.GetProductLineEditModel, id);

            // Resolve response.
            return ManageGetDataResponse<EditProductLineViewModel>(getModel);
        }

        // POST: ProductLines/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditProductLineViewModel model)
        {
            // Check given ID is valid.
            if (model.Id < 1) return IdIsNotValid(EntityNames.ProductLine);

            if (!ModelState.IsValid)
                return await ModelStateInvalid(model, EntityNames.ProductLine);

            // Try update ProductLine.
            var update = await _dataService.UpdateAsync(ApiUrls.UpdateProductLine, model);

            // Resolve response.
            return ManageInputResponse(update);
        }


        // GET: ProductLines/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id < 1) return IdIsNotValid(EntityNames.ProductLine);

            // Try get Model.
            var getModel = await _dataService.GetAsync<DisplayProductLineViewModel>(ApiUrls.GetProductLineDisplay, id);

            // Resolve response.
            return ManageGetDataResponse<DisplayProductLineViewModel>(getModel);
        }

        // POST: ProductLines/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            // Check given ID is valid.
            if (id < 1) return IdIsNotValid(EntityNames.ProductLine);

            // Try delete ProductLine.
            var delete = await _dataService.DeleteAsync(ApiUrls.DeleteProductLine, id);

            // Resolve response.
            return ManageDeleteResponse(delete);
        }
    }
}

WiseSwitch/Controllers/ProductSeriesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WiseSwitch.Services.Api;
using WiseSwitch.Services.Data;
using WiseSwitch.Utils;
using WiseSwitch.ViewModels.Entities.ProductSeries;

namespace WiseSwitch.Controllers
{
    [Authorize(Roles = "Admin,Technician")]
    public class ProductSeriesController : AppController
    {
        private readonly DataService _dataService;

        protected override async Task GetInputCombos()
        {
            var getCombo = await _dataService.GetAsync<IEnumerable<SelectListItem>>(ApiUrls.GetBrandsCombo, null);
            if (getCombo.IsSuccess)
            {
                ViewBag.ComboBrands = getCombo.Result;
            }
            else throw new Exception("Could not get input combo from API.");
        }

        public ProductSeriesController(DataService dataService)
        {
            _dataService = dataService;
        }


        // GET: ProductSeries
        public async Task<IActionResult> Index()
        {
            var getAll = await _dataService.GetAsync<IEnumerable<IndexRowProductSeriesViewModel>>(ApiUrls.GetAllProductSeries);

            return ManageGetDataResponse<IEnumerable<IndexRowProductSeriesViewModel>>(getAll);
        }


        // GET: ProductSeries/5
        public async Task<IActionResult> Details(int id)
        {
            // Check given ID is valid.
            if (id < 1) return IdIsNotValid(EntityNames.ProductSeries);

            // Try get model.
            var getModel = await _dataService.GetAsync<DisplayProductSeriesViewModel>(ApiUrls.GetProductSeriesDisplay, id);

            // Resolve response.
            return ManageGetDataResponse<DisplayProductSeriesViewModel>(getModel);
        }


        // GET: ProductSeries/Create
        public async Task<IActionResult> Create(int productLineId)
        {
            // Default behavior - no ID has been given for the Product Series' Product Line.
            if (productLineId < 1)
            {
                return await ViewInput(null);
            }

            // -- If the user gives an ID for the ProductSeries' Product Line --

            var getBrandId = await _dataService.GetAsync<int>(ApiUrls.GetProductLineBrandId, productLineId);
            if (getBrandId.IsSuccess)
            {
                if (getBrandId.Result is int brandId)
                {
                    if (brandId < 1) return NotFound(EntityNames.Brand);

                    var model = new CreateProductSeriesViewModel
                    {
                        BrandId = brandId,
                        ProductLineId = productLineId,
                    };

                    return await ViewInput(model);
                }
            }

            return ResponseIsNotSuccessful(getBrandId);
        }

        // POST: ProductSeries/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateProductSeriesViewModel model)
        {
            if (!ModelState.IsValid)
                return await ModelStateInvalid(model, EntityNames.ProductSeries);

            // Try create ProductSeries.
            var create = await _dataService.CreateAsync(ApiUrls.CreateProductSeries, model);

            // Resolve response.
            return ManageInputResponse(create);
        }

        // GET: ProductSeries/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            // Check given ID is valid.
            if (id < 1) return IdIsNotValid(EntityNames.ProductSeries);

            // Try to get model.
            var getModel = await _dataService.GetAsync<EditProductSeriesViewModel>(ApiUrls.GetProductSeriesEditModel, id);

            // Resolve response.
            return ManageGetDataResponse<EditProductSeriesViewModel>(getModel);
        }

        // POST: ProductSeries/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditProductSeriesViewModel model)
        {
            // Check given ID is valid.
            if (model.Id < 1) return IdIsNotValid(EntityNames.ProductSeries);

            if (!ModelState.IsValid)
                return await ModelStateInvalid(model, EntityNames.ProductSeries);

            // Try update ProductSeries.
            var update = await _dataService.UpdateAsync(ApiUrls.UpdateProductSeries, model);

            // Resolve response.
            return ManageInputResponse(update);
        }


        // GET: ProductSeries/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id < 1) return IdIsNotValid(EntityNames.ProductSeries);

            // Try get Model.
            var getModel = await _dataService.GetAsync<DisplayProductSeriesViewModel>(ApiUrls.GetProductSeriesDisplay, id);

            // Resolve response.
            return ManageGetDataResponse<DisplayProductSeriesViewModel>(getModel);
        }

        // POST: ProductSeries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            // Check given ID is valid.
            if (id < 1) return IdIsNotValid(EntityNames.ProductSeries);

            // Try delete ProductSeries.
            var delete = await _dataService.DeleteAsync(ApiUrls.DeleteProductSeries, id);

            // Resolve response.
            return ManageDeleteResponse(delete);
        }
    }
}

WiseSwitch/Views/ProductLines/Create.cshtml
@model WiseSwitch.ViewModels.Entities.ProductLine.CreateProductLineViewModel

@{
    ViewData["Title"] = "New product line";
}

<h2><partial name="_GoBackFaIcon" /> New Product Line</h2>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">

            @* ModelState Errors *@
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <!-- Brand -->
            <div class="mb-3">
                <label asp-for="BrandId" class="form-label"></label>
                <select asp-for="BrandId" asp-items="ViewBag.ComboBrands" class="form-select">
                    <option disabled selected value="0">Select a Brand</option>
                </select>
                <span asp-validation-for="BrandId" class="text-danger"></span>
            </div>

            <!-- Name -->
            <div class="mb-3">
                <label asp-for="Name" class="form-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <hr />

            <!-- Add -->
            <div class="mb-3">
                <button class="btn btn-primary"><i class="fa fa-save"></i> Add</button>
            </div>

        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("Scripts/_ValidationScriptsPartial");
    }
}

WiseSwitch/Views/ProductLines/Delete.cshtml
@model WiseSwitch.ViewModels.Entities.ProductLine.DisplayProductLineViewModel

@{
    ViewData["Title"] = "Delete product line";
}

<h2><partial name="_GoBackFaIcon" /> Delete Product Line @Model.Name</h2>

<div>
    
    @* ModelState Errors - in case delete fails. *@
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <hr />

    @* Check whether this Product Line has any Product Series registered in the database. *@
    @if (!Model.ProductSeriesNames.Any())
    {
        <p>Are you sure you want to delete this Product Line?</p>

        <form asp-action="Delete">
            <button type="submit" value="@Model.Id" class="btn btn-danger">Delete</button>
        </form>
    }
    else
    {
        <p>You can't delete this Product Line because it has at least one Product Series registered in the database.</p>
        <ul>
            @foreach (var item in Model.ProductSeriesNames)
            {
                <li>@item</li>
            }
        </ul>
    }

</div>

WiseSwitch/Views/ProductLines/Details.cshtml
@model WiseSwitch.ViewModels.Entities.ProductLine.DisplayProductLineViewModel

@{
    ViewData["Title"] = $"Product Line - {Model.Name}";
}

<h2><partial name="_GoBackFAIcon" /> @Model.Name</h2>
<hr />

<div>
    <h4>Brand</h4>
    <p>@Model.BrandName</p>

    <!-- List of Product Series -->
    <h4>ProductSeries</h4>
    @if (!Model.ProductSeriesNames.Any())
    {
        <p>This Product Line has no Product Series registered in the database.</p>
    }
    else
    {
        <ul>
            @foreach (var item in Model.ProductSeriesNames)
            {
                <li>@item</li>
            }
        </ul>
    }
</div>

<div>
    <hr />
    <div class="form-group">
        <a asp-controller="ProductSeries" asp-action="Create" asp-route-productLineId="@Model.Id" class="btn btn-success"><i class="fa fa-square-plus"></i> New Product Series</a>
        <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary"><i class="fa fa-edit"></i> Edit</a>
        <a asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger"><i class="fa fa-xmark"></i> Delete</a>
    </div>
</div>

WiseSwitch/Views/ProductLines/Edit.cshtml
@model WiseSwitch.ViewModels.Entities.ProductLine.EditProductLineViewModel

@{
    ViewData["Title"] = "Edit product line";
}

<h2><partial name="_GoBackFaIcon" /> Edit Product Line</h2>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">

            @* ModelState Errors *@
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            @* Id for Edit *@
            <input type="hidden" asp-for="Id" />

            <!-- Brand -->
            <div class="mb-3">
                <label asp-for="BrandId" class="form-label"></label>
                <select asp-for="BrandId" asp-items="ViewBag.ComboBrands" class="form-select"></select>
                <span asp-validation-for="BrandId" class="text-danger"></span>
            </div>

            <!-- Name -->
            <div class="mb-3">
                <label asp-for="Name" class="form-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <hr />

            <!-- Save -->
            <div class="mb-3">
                <button class="btn btn-primary"><i class="fa fa-save"></i> Save</button>
            </div>

        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("Scripts/_ValidationScriptsPartial");
    }
}

WiseSwitch/Views/ProductLines/Index.cshtml
@model IEnumerable<WiseSwitch.ViewModels.Entities.ProductLine.IndexRowProductLineViewModel>

@{
    ViewData["Title"] = "Product Lines";
}

<link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap4.min.css" />

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h1 class="panel-title">Product Lines</h1>
                <p>
                    <a asp-action="Create" class="btn btn-success"><i class="fa fa-square-plus"></i> New Product Line</a>
                </p>
            </div>
            <div class="panel-body">
                <table class="table table-hover" id="MyTable">
                     <thead>
                        <tr>
                            @* <th><!-- # --></th> *@
                            <th>
                                @Html.DisplayNameFor(model => model.BrandName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Name)
                            </th>
                            <th><!-- actions --></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                @* <td>#</td> *@
                                <td>
                                    @Html.DisplayFor(modelItem => item.BrandName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-success"><i class="fa fa-list"></i></a>
                                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary"><i class="fa fa-edit"></i></a>
                                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger"><i class="fa fa-trash"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    @{
        await Html.RenderPartialAsync("Scripts/_DataTablesScriptsPartial");
    }
}