WiseSwitch/ViewModels/Entities/ProductSeries/CreateProductSeriesViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WiseSwitch.ViewModels.Entities.ProductSeries
{
    public class CreateProductSeriesViewModel : IInputViewModel
    {
        [Required(ErrorMessage = "A Name is required for the Product Series.")]
        public string Name { get; set; }


        [Display(Name = "Product Line")]
        [Range(1, int.MaxValue, ErrorMessage = "The ID for the Product Line is not valid.")]
        public int ProductLineId { get; set; }


        [Display(Name = "Brand")]
        [Range(1, int.MaxValue, ErrorMessage = "The ID for the Brand is not valid.")]
        public int BrandId { get; set; }
    }
}

WiseSwitch/ViewModels/Entities/ProductSeries/DisplayProductSeriesViewModel.cs
namespace WiseSwitch.ViewModels.Entities.ProductSeries
{
    public class DisplayProductSeriesViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }


        public string ProductLineName { get; set; }

        public string BrandName { get; set; }


        public IEnumerable<string> SwitchModelsNames { get; set; }
    }
}

WiseSwitch/ViewModels/Entities/ProductSeries/EditProductSeriesViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WiseSwitch.ViewModels.Entities.ProductSeries
{
    public class EditProductSeriesViewModel : IInputViewModel
    {
        public int Id { get; set; }


        [Required(ErrorMessage = "A Name is required for the Product Series.")]
        public string Name { get; set; }


        [Display(Name = "Product Line")]
        [Range(1, int.MaxValue, ErrorMessage = "The ID for the Product Line is not valid.")]
        public int ProductLineId { get; set; }


        [Display(Name = "Brand")]
        [Range(1, int.MaxValue, ErrorMessage = "The ID for the Brand is not valid.")]
        public int BrandId { get; set; }
    }
}

WiseSwitch/ViewModels/Entities/ProductSeries/IndexRowProductSeriesViewModel.cs
namespace WiseSwitch.ViewModels.Entities.ProductSeries
{
    public class IndexRowProductSeriesViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }


        public string ProductLineName { get; set; }

        public string BrandName { get; set; }
    }
}

WiseSwitch/ViewModels/Entities/ProductSeries/InputProductSeriesViewModel.cs
namespace WiseSwitch.ViewModels.Entities.ProductSeries
{
    public class InputProductSeriesViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public int ProductLineId { get; set; }

        public int BrandId { get; set; }
    }
}

WiseSwitch/Controllers/ProductSeriesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WiseSwitch.Services.Api;
using WiseSwitch.Services.Data;
using WiseSwitch.Utils;
using WiseSwitch.ViewModels.Entities.ProductSeries;

namespace WiseSwitch.Controllers
{
    [Authorize(Roles = "Admin,Technician")]
    public class ProductSeriesController : AppController
    {
        private readonly DataService _dataService;

        protected override async Task GetInputCombos()
        {
            var getCombo = await _dataService.GetAsync<IEnumerable<SelectListItem>>(ApiUrls.GetBrandsCombo, null);
            if (getCombo.IsSuccess)
            {
                ViewBag.ComboBrands = getCombo.Result;
            }
            else throw new Exception("Could not get input combo from API.");
        }

        public ProductSeriesController(DataService dataService)
        {
            _dataService = dataService;
        }


        // GET: ProductSeries
        public async Task<IActionResult> Index()
        {
            var getAll = await _dataService.GetAsync<IEnumerable<IndexRowProductSeriesViewModel>>(ApiUrls.GetAllProductSeries);

            return ManageGetDataResponse<IEnumerable<IndexRowProductSeriesViewModel>>(getAll);
        }


        // GET: ProductSeries/5
        public async Task<IActionResult> Details(int id)
        {
            // Check given ID is valid.
            if (id < 1) return IdIsNotValid(EntityNames.ProductSeries);

            // Try get model.
            var getModel = await _dataService.GetAsync<DisplayProductSeriesViewModel>(ApiUrls.GetProductSeriesDisplay, id);

            // Resolve response.
            return ManageGetDataResponse<DisplayProductSeriesViewModel>(getModel);
        }


        // GET: ProductSeries/Create
        public async Task<IActionResult> Create(int productLineId)
        {
            // Default behavior - no ID has been given for the Product Series' Product Line.
            if (productLineId < 1)
            {
                return await ViewInput(null);
            }

            // -- If the user gives an ID for the ProductSeries' Product Line --

            var getBrandId = await _dataService.GetAsync<int>(ApiUrls.GetProductLineBrandId, productLineId);
            if (getBrandId.IsSuccess)
            {
                if (getBrandId.Result is int brandId)
                {
                    if (brandId < 1) return NotFound(EntityNames.Brand);

                    var model = new CreateProductSeriesViewModel
                    {
                        BrandId = brandId,
                        ProductLineId = productLineId,
                    };

                    return await ViewInput(model);
                }
            }

            return ResponseIsNotSuccessful(getBrandId);
        }

        // POST: ProductSeries/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateProductSeriesViewModel model)
        {
            if (!ModelState.IsValid)
                return await ModelStateInvalid(model, EntityNames.ProductSeries);

            // Try create ProductSeries.
            var create = await _dataService.CreateAsync(ApiUrls.CreateProductSeries, model);

            // Resolve response.
            return ManageInputResponse(create);
        }

        // GET: ProductSeries/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            // Check given ID is valid.
            if (id < 1) return IdIsNotValid(EntityNames.ProductSeries);

            // Try to get model.
            var getModel = await _dataService.GetAsync<EditProductSeriesViewModel>(ApiUrls.GetProductSeriesEditModel, id);

            // Resolve response.
            return ManageGetDataResponse<EditProductSeriesViewModel>(getModel);
        }

        // POST: ProductSeries/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditProductSeriesViewModel model)
        {
            // Check given ID is valid.
            if (model.Id < 1) return IdIsNotValid(EntityNames.ProductSeries);

            if (!ModelState.IsValid)
                return await ModelStateInvalid(model, EntityNames.ProductSeries);

            // Try update ProductSeries.
            var update = await _dataService.UpdateAsync(ApiUrls.UpdateProductSeries, model);

            // Resolve response.
            return ManageInputResponse(update);
        }


        // GET: ProductSeries/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id < 1) return IdIsNotValid(EntityNames.ProductSeries);

            // Try get Model.
            var getModel = await _dataService.GetAsync<DisplayProductSeriesViewModel>(ApiUrls.GetProductSeriesDisplay, id);

            // Resolve response.
            return ManageGetDataResponse<DisplayProductSeriesViewModel>(getModel);
        }

        // POST: ProductSeries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            // Check given ID is valid.
            if (id < 1) return IdIsNotValid(EntityNames.ProductSeries);

            // Try delete ProductSeries.
            var delete = await _dataService.DeleteAsync(ApiUrls.DeleteProductSeries, id);

            // Resolve response.
            return ManageDeleteResponse(delete);
        }
    }
}

WiseSwitch/Controllers/SwitchModelsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WiseSwitch.Services.Api;
using WiseSwitch.Services.Data;
using WiseSwitch.Utils;
using WiseSwitch.ViewModels.Entities.SwitchModel;

namespace WiseSwitch.Controllers
{
    [Authorize(Roles = "Admin,Technician")]
    public class SwitchModelsController : AppController
    {
        private readonly DataService _dataService;

        protected override async Task GetInputCombos()
        {
            var getComboBrands = await _dataService.GetAsync<IEnumerable<SelectListItem>>(ApiUrls.GetBrandsCombo, null);
            if (getComboBrands.IsSuccess)
            {
                ViewBag.ComboBrands = getComboBrands.Result;
            }
            else throw new Exception("Could not get input combo from API.");

            var getComboFirmwareVersions = await _dataService.GetAsync<IEnumerable<SelectListItem>>(ApiUrls.GetFirmwareVersionsCombo, null);
            if (getComboFirmwareVersions.IsSuccess)
            {
                ViewBag.ComboFirmwareVersions = getComboFirmwareVersions.Result;
            }
            else throw new Exception("Could not get input combo from API.");
        }

        public SwitchModelsController(DataService dataService)
        {
            _dataService = dataService;
        }


        // GET: SwitchModels
        public async Task<IActionResult> Index()
        {
            var getAll = await _dataService.GetAsync<IEnumerable<IndexRowSwitchModelViewModel>>(ApiUrls.GetAllSwitchModels);

            return ManageGetDataResponse<IEnumerable<IndexRowSwitchModelViewModel>>(getAll);
        }


        // GET: SwitchModels/5
        public async Task<IActionResult> Details(int id)
        {
            // Check given ID is valid.
            if (id < 1) return IdIsNotValid(EntityNames.SwitchModel);

            // Try get model.
            var getModel = await _dataService.GetAsync<DisplaySwitchModelViewModel>(ApiUrls.GetSwitchModelDisplay, id);

            // Resolve response.
            return ManageGetDataResponse<DisplaySwitchModelViewModel>(getModel);
        }


        // GET: SwitchModels/Create
        public async Task<IActionResult> Create(int productSeriesId)
        {
            // Default behavior - no ID has been given for the SwitchModel's Product Series.
            if (productSeriesId < 1)
            {
                return await ViewInput(null);
            }

            // -- If the user gave an ID for the Switch Model's Product Series --

            // Get Dependency Chain IDs.
            var getDependencyChainIds = await _dataService.GetAsync<ProductSeriesDependencyChainIds>(ApiUrls.GetProductSeriesDependencyChainIds, productSeriesId);
            if (getDependencyChainIds.IsSuccess)
            {
                if (getDependencyChainIds.Result is ProductSeriesDependencyChainIds dependencyChainIds)
                {
                    if (dependencyChainIds == null) return NotFound(EntityNames.ProductSeries);

                    var model = new CreateSwitchModelViewModel
                    {
                        ProductSeriesId = productSeriesId,
                        ProductLineId = dependencyChainIds.ProductLineId,
                        BrandId = dependencyChainIds.BrandId,
                    };

                    return await ViewInput(model);
                }
            }

            return ResponseIsNotSuccessful(getDependencyChainIds);
        }

        // POST: SwitchModels/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateSwitchModelViewModel model)
        {
            if (!ModelState.IsValid)
                return await ModelStateInvalid(model, EntityNames.SwitchModel);

            // Try create SwitchModel.
            var create = await _dataService.CreateAsync(ApiUrls.CreateSwitchModel, model);

            // Resolve response.
            return ManageInputResponse(create);
        }

        // GET: SwitchModels/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            // Check given ID is valid.
            if (id < 1) return IdIsNotValid(EntityNames.SwitchModel);

            // Try to get model.
            var getModel = await _dataService.GetAsync<EditSwitchModelViewModel>(ApiUrls.GetSwitchModelEditModel, id);

            // Resolve response.
            return ManageGetDataResponse<EditSwitchModelViewModel>(getModel);
        }

        // POST: SwitchModels/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditSwitchModelViewModel model)
        {
            // Check given ID is valid.
            if (model.Id < 1) return IdIsNotValid(EntityNames.SwitchModel);

            if (!ModelState.IsValid)
                return await ModelStateInvalid(model, EntityNames.SwitchModel);

            // Try update SwitchModel.
            var update = await _dataService.UpdateAsync(ApiUrls.UpdateSwitchModel, model);

            // Resolve response.
            return ManageInputResponse(update);
        }


        // GET: SwitchModels/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id < 1) return IdIsNotValid(EntityNames.SwitchModel);

            // Try get Model.
            var getModel = await _dataService.GetAsync<DisplaySwitchModelViewModel>(ApiUrls.GetSwitchModelDisplay, id);

            // Resolve response.
            return ManageGetDataResponse<DisplaySwitchModelViewModel>(getModel);
        }

        // POST: SwitchModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            // Check given ID is valid.
            if (id < 1) return IdIsNotValid(EntityNames.SwitchModel);

            // Try delete SwitchModel.
            var delete = await _dataService.DeleteAsync(ApiUrls.DeleteSwitchModel, id);

            // Resolve response.
            return ManageDeleteResponse(delete);
        }
    }
}

WiseSwitch/Views/ProductSeries/Create.cshtml
@model WiseSwitch.ViewModels.Entities.ProductSeries.CreateProductSeriesViewModel

@{
    ViewData["Title"] = "New product series";
}

<h2><partial name="_GoBackFaIcon" /> New Product Series</h2>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">

            @* ModelState Errors *@
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <!-- Brand -->
            <div class="mb-3">
                <label asp-for="BrandId" class="form-label"></label>
                <select asp-for="BrandId" asp-items="ViewBag.ComboBrands" class="form-select" onchange="getProductLines()">
                    <option disabled selected value="0">Select a Brand</option>
                </select>
                <span asp-validation-for="BrandId" class="text-danger"></span>
            </div>

            <!-- Get Combo Product Lines when Brand is selected. -->
            <script>
                const getProductLines = (selectedValue) => {
                    // Get Combo from API: (selectElementId, friendlyEntityName, pluralFriendlyEntityName, mvcActionName, fkName, fkValue, selectedValue)
                    getSelectOptionsFromApi("ProductLineId", "Product Line", "Product Lines", "ComboProductLinesOfBrand", "BrandId", $('#BrandId').val(), selectedValue);
                }
            </script>

            <!-- Product Line -->
            <div class="mb-3">
                <label asp-for="ProductLineId" class="form-label"></label>
                <select asp-for="ProductLineId" class="form-select">
                    <option disabled selected value="0">Select a Brand</option>
                </select>
                <span asp-validation-for="ProductLineId" class="text-danger"></span>
            </div>

            <!-- Name -->
            <div class="mb-3">
                <label asp-for="Name" class="form-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <hr />

            <!-- Add -->
            <div class="mb-3">
                <button class="btn btn-primary"><i class="fa fa-save"></i> Add</button>
            </div>

        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("Scripts/_ValidationScriptsPartial");
        await Html.RenderPartialAsync("Scripts/_GetSelectOptionsAjaxScript");

        @* Get sibling Combo Product Lines if ProductLineId is given. *@
        @if (Model != null)
        {
            <!-- Get sibling Combo Product Lines if ProductLineId is given on Create. -->
            <script>$(getProductLines(@Model.ProductLineId))</script>
        }
    }
}

WiseSwitch/Views/ProductSeries/Delete.cshtml
@model WiseSwitch.ViewModels.Entities.ProductSeries.DisplayProductSeriesViewModel

@{
    ViewData["Title"] = "Delete product series";
}

<h2><partial name="_GoBackFaIcon" /> Delete Product Series</h2>

<div>

    @* ModelState Errors - in case delete fails. *@
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <hr />

    @* Check whether this Product Series has any Switch Model registered in the database. *@
    @if (!Model.SwitchModelsNames.Any())
    {
        <p>Are you sure you want to delete this Product Series?</p>

        <form asp-action="Delete">
            <button type="submit" value="@Model.Id" class="btn btn-danger">Delete</button>
        </form>
    }
    else
    {
        <p>You can't delete this Product Series because it has at least one Switch Model registered in the database.</p>
        <ul>
            @foreach (var item in Model.SwitchModelsNames)
            {
                <li>@item</li>
            }
        </ul>
    }

</div>

WiseSwitch/Views/ProductSeries/Details.cshtml
@model WiseSwitch.ViewModels.Entities.ProductSeries.DisplayProductSeriesViewModel

@{
    ViewData["Title"] = $"Product Series - {Model.Name}";
}

<h2><partial name="_GoBackFAIcon" /> @Model.ProductLineName @Model.Name</h2>
<hr />

<div>
    <h4>Brand</h4>
    <p>@Model.BrandName</p>

    <!-- List of Switch Models -->
    <h4>SwitchModels</h4>
    @if (!Model.SwitchModelsNames.Any())
    {
        <p>This Product Series has no Switch Models registered in the database.</p>
    }
    else
    {
        <ul>
            @foreach (var item in Model.SwitchModelsNames)
            {
                <li>@item</li>
            }
        </ul>
    }
</div>

<div>
    <hr />
    <div class="form-group">
        <a asp-controller="SwitchModels" asp-action="Create" asp-route-productSeriesId="@Model.Id" class="btn btn-success"><i class="fa fa-square-plus"></i> New Switch Model</a>
        <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary"><i class="fa fa-edit"></i> Edit</a>
        <a asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger"><i class="fa fa-xmark"></i> Delete</a>
    </div>
</div>

WiseSwitch/Views/ProductSeries/Edit.cshtml
@model WiseSwitch.ViewModels.Entities.ProductSeries.EditProductSeriesViewModel

@{
    ViewData["Title"] = "Edit product series";
}

<h2><partial name="_GoBackFaIcon" /> Edit Product Series</h2>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">

            @* ModelState Errors *@
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            @* Id for Edit *@
            <input type="hidden" asp-for="Id" />

            <!-- Brand -->
            <div class="mb-3">
                <label asp-for="BrandId" class="form-label"></label>
                <select asp-for="BrandId" asp-items="ViewBag.ComboBrands" class="form-select" onchange="getProductLines()"></select>
                <span asp-validation-for="BrandId" class="text-danger"></span>
            </div>

            <!-- Get Combo Product Lines when Brand is selected. -->
            <script>
                const getProductLines = (selectedValue) => {
                    // Get Combo from API: (selectElementId, friendlyEntityName, pluralFriendlyEntityName, mvcActionName, fkName, fkValue, selectedValue)
                    getSelectOptionsFromApi("ProductLineId", "Product Line", "Product Lines", "ComboProductLinesOfBrand", "BrandId", $('#BrandId').val(), selectedValue);
                }
            </script>

            <!-- ProductLine -->
            <div class="mb-3">
                <label asp-for="ProductLineId" class="form-label"></label>
                <select asp-for="ProductLineId" class="form-select"></select>
                <span asp-validation-for="ProductLineId" class="text-danger"></span>
            </div>

            <!-- Name -->
            <div class="mb-3">
                <label asp-for="Name" class="form-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <hr />

            <!-- Save -->
            <div class="mb-3">
                <button class="btn btn-primary"><i class="fa fa-save"></i> Save</button>
            </div>

        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("Scripts/_ValidationScriptsPartial");
        await Html.RenderPartialAsync("Scripts/_GetSelectOptionsAjaxScript");

        <!-- Get sibling Combo Product Lines on Edit. -->
        <script>$(getProductLines(@Model.ProductLineId))</script>
    }
}

WiseSwitch/Views/ProductSeries/Index.cshtml
@model IEnumerable<WiseSwitch.ViewModels.Entities.ProductSeries.IndexRowProductSeriesViewModel>

@{
    ViewData["Title"] = "Product Series";
}

<link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap4.min.css" />

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h1 class="panel-title">Product Series</h1>
                <p>
                    <a asp-action="Create" class="btn btn-success"><i class="fa fa-square-plus"></i> New Product Series</a>
                </p>
            </div>
            <div class="panel-body">
                <table class="table table-hover" id="MyTable">
                    <thead>
                        <tr>
                            @* <th><!-- # --></th> *@
                            <th>
                                @Html.DisplayNameFor(model => model.BrandName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ProductLineName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Name)
                            </th>
                            <th><!-- actions --></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                @* <td>#</td> *@
                                <td>
                                    @Html.DisplayFor(modelItem => item.BrandName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ProductLineName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-success"><i class="fa fa-list"></i></a>
                                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary"><i class="fa fa-edit"></i></a>
                                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger"><i class="fa fa-trash"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    @{
        await Html.RenderPartialAsync("Scripts/_DataTablesScriptsPartial");
    }
}