WiseSwitch/ViewModels/NotFoundViewModel.cs
namespace WiseSwitch.ViewModels
{
    public class NotFoundViewModel
    {
        public string Title { get; set; }

        public string Message { get; set; }
    }
}

WiseSwitch/Controllers/BrandsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WiseSwitch.Services.Api;
using WiseSwitch.Services.Data;
using WiseSwitch.Utils;
using WiseSwitch.ViewModels.Entities.Brand;

namespace WiseSwitch.Controllers
{
    [Authorize(Roles = "Admin,Technician")]
    public class BrandsController : AppController
    {
        private readonly DataService _dataService;

        protected override async Task GetInputCombos()
        {
            var getCombo = await _dataService.GetAsync<IEnumerable<SelectListItem>>(ApiUrls.GetManufacturersCombo, null);
            if (getCombo.IsSuccess)
            {
                ViewBag.ComboManufacturers = getCombo.Result;
            }
            else throw new Exception("Could not get input combo from API.");
        }

        public BrandsController(DataService dataService)
        {
            _dataService = dataService;
        }


        // GET: Brands
        public async Task<IActionResult> Index()
        {
            //return await _helper.GetIndexAsync<IEnumerable<IndexRowBrandViewModel>>(EntityNames.Brand);
            var getAll = await _dataService.GetAsync<IEnumerable<IndexRowBrandViewModel>>(ApiUrls.GetAllBrands);
            
            return ManageGetDataResponse<IEnumerable<IndexRowBrandViewModel>>(getAll);
        }


        // GET: Brands/5
        public async Task<IActionResult> Details(int id)
        {
            // Check given ID is valid.
            if (id < 1) return IdIsNotValid(EntityNames.Brand);

            // Try get model.
            var getModel = await _dataService.GetAsync<DisplayBrandViewModel>(ApiUrls.GetBrandDisplay, id);

            // Resolve response.
            return ManageGetDataResponse<DisplayBrandViewModel>(getModel);
        }


        // GET: Brands/Create
        public async Task<IActionResult> Create(int manufacturerId)
        {
            var model = manufacturerId < 1 ? null : new CreateBrandViewModel { ManufacturerId = manufacturerId };

            return await ViewInput(model);
        }

        // POST: Brands/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateBrandViewModel model)
        {
            if (!ModelState.IsValid)
                return await ModelStateInvalid(model, EntityNames.Brand);

            // Try create Brand.
            var create = await _dataService.CreateAsync(ApiUrls.CreateBrand, model);

            // Resolve response.
            return ManageInputResponse(create);
        }

        // GET: Brands/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            // Check given ID is valid.
            if (id < 1) return IdIsNotValid(EntityNames.Brand);

            // Try to get model.
            var getModel = await _dataService.GetAsync<EditBrandViewModel>(ApiUrls.GetBrandEditModel, id);

            // Resolve response.
            return ManageGetDataResponse<EditBrandViewModel>(getModel);
        }

        // POST: Brands/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditBrandViewModel model)
        {
            // Check given ID is valid.
            if (model.Id < 1) return IdIsNotValid(EntityNames.Brand);

            if (!ModelState.IsValid)
                return await ModelStateInvalid(model, EntityNames.Brand);

            // Try update Brand.
            var update = await _dataService.UpdateAsync(ApiUrls.UpdateBrand, model);

            // Resolve response.
            return ManageInputResponse(update);
        }


        // GET: Brands/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id < 1) return IdIsNotValid(EntityNames.Brand);

            // Try get Model.
            var getModel = await _dataService.GetAsync<DisplayBrandViewModel>(ApiUrls.GetBrandDisplay, id);

            // Resolve response.
            return ManageGetDataResponse<DisplayBrandViewModel>(getModel);
        }

        // POST: Brands/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            // Check given ID is valid.
            if (id < 1) return IdIsNotValid(EntityNames.Brand);

            // Try delete Brand.
            var delete = await _dataService.DeleteAsync(ApiUrls.DeleteBrand, id);

            // Resolve response.
            return ManageDeleteResponse(delete);
        }
    }
}

WiseSwitch/Controllers/ProductLinesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WiseSwitch.Services.Api;
using WiseSwitch.Services.Data;
using WiseSwitch.Utils;
using WiseSwitch.ViewModels.Entities.ProductLine;

namespace WiseSwitch.Controllers
{
    [Authorize(Roles = "Admin,Technician")]
    public class ProductLinesController : AppController
    {
        private readonly DataService _dataService;

        protected override async Task GetInputCombos()
        {
            var getCombo = await _dataService.GetAsync<IEnumerable<SelectListItem>>(ApiUrls.GetBrandsCombo, null);
            if (getCombo.IsSuccess)
            {
                ViewBag.ComboBrands = getCombo.Result;
            }
            else throw new Exception("Could not get input combo from API.");
        }

        public ProductLinesController(DataService dataService)
        {
            _dataService = dataService;
        }


        // GET: ProductLines
        public async Task<IActionResult> Index()
        {
            var getAll = await _dataService.GetAsync<IEnumerable<IndexRowProductLineViewModel>>(ApiUrls.GetAllProductLines);

            return ManageGetDataResponse<IEnumerable<IndexRowProductLineViewModel>>(getAll);
        }


        // GET: ProductLines/5
        public async Task<IActionResult> Details(int id)
        {
            // Check given ID is valid.
            if (id < 1) return IdIsNotValid(EntityNames.ProductLine);

            // Try get model.
            var getModel = await _dataService.GetAsync<DisplayProductLineViewModel>(ApiUrls.GetProductLineDisplay, id);

            // Resolve response.
            return ManageGetDataResponse<DisplayProductLineViewModel>(getModel);
        }


        // GET: ProductLines/Create
        public async Task<IActionResult> Create(int brandId)
        {
            var model = brandId < 1 ? null : new CreateProductLineViewModel { BrandId = brandId };

            return await ViewInput(model);
        }

        // POST: ProductLines/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateProductLineViewModel model)
        {
            if (!ModelState.IsValid)
                return await ModelStateInvalid(model, EntityNames.ProductLine);

            // Try create ProductLine.
            var create = await _dataService.CreateAsync(ApiUrls.CreateProductLine, model);

            // Resolve response.
            return ManageInputResponse(create);
        }

        // GET: ProductLines/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            // Check given ID is valid.
            if (id < 1) return IdIsNotValid(EntityNames.ProductLine);

            // Try to get model.
            var getModel = await _dataService.GetAsync<EditProductLineViewModel>(ApiUrls.GetProductLineEditModel, id);

            // Resolve response.
            return ManageGetDataResponse<EditProductLineViewModel>(getModel);
        }

        // POST: ProductLines/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditProductLineViewModel model)
        {
            // Check given ID is valid.
            if (model.Id < 1) return IdIsNotValid(EntityNames.ProductLine);

            if (!ModelState.IsValid)
                return await ModelStateInvalid(model, EntityNames.ProductLine);

            // Try update ProductLine.
            var update = await _dataService.UpdateAsync(ApiUrls.UpdateProductLine, model);

            // Resolve response.
            return ManageInputResponse(update);
        }


        // GET: ProductLines/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id < 1) return IdIsNotValid(EntityNames.ProductLine);

            // Try get Model.
            var getModel = await _dataService.GetAsync<DisplayProductLineViewModel>(ApiUrls.GetProductLineDisplay, id);

            // Resolve response.
            return ManageGetDataResponse<DisplayProductLineViewModel>(getModel);
        }

        // POST: ProductLines/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            // Check given ID is valid.
            if (id < 1) return IdIsNotValid(EntityNames.ProductLine);

            // Try delete ProductLine.
            var delete = await _dataService.DeleteAsync(ApiUrls.DeleteProductLine, id);

            // Resolve response.
            return ManageDeleteResponse(delete);
        }
    }
}

WiseSwitch/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WiseSwitch.Data;
using WiseSwitch.Data.Identity;
using WiseSwitch.Exceptions;
using WiseSwitch.Exceptions.UsersControllerExceptions;
using WiseSwitch.ViewModels;
using WiseSwitch.ViewModels.Entities.User;

namespace WiseSwitch.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly IDataUnit _dataUnit;

        public UsersController(IDataUnit dataUnit)
        {
            _dataUnit = dataUnit;
        }


        // GET: UsersController
        public async Task<IActionResult> Index()
        {
            var users = await _dataUnit.Users
                .GetAllOrderByPropertiesAsync(
                    nameof(AppUser.Role),
                    nameof(AppUser.UserName));

            return View(users);
        }


        // GET: UsersController/Create
        public async Task<IActionResult> Create()
        {
            return await ViewInputAsync(null);
        }

        // POST: UsersController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(UserViewModel model)
        {
            // Id is not needed when creating User.
            ModelState.Remove(nameof(model.Id));

            if (!ModelState.IsValid)
                return await ModelStateInvalid(model);

            try
            {
                var user = new AppUser { UserName = model.UserName.Trim(), Role = model.Role };

                var createUserInRole = await _dataUnit.Users.CreateInRoleAsync(user, model.Password, model.Role);
                if (createUserInRole.Succeeded)
                {
                    return Success($"User created: {user.UserName}, {user.Role}.");
                }
                else
                {
                    if (createUserInRole.Errors.Any(error => error.Code == "InvalidUserName"))
                    {
                        ModelState.AddModelError(string.Empty, "Username is not valid.");
                        return await ViewInputAsync(model);
                    }
                }
            }
            catch { }

            ModelState.AddModelError(string.Empty, "Could not create User.");
            return await ViewInputAsync(model);
        }


        // GET: UsersController/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (!IsIdValid(id)) return IdIsNotValid();

            var model = await _dataUnit.Users.GetUserViewModelAsync(id);
            if (model == null) return UserNotFound();

            return await ViewInputAsync(model);
        }

        // POST: UsersController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(UserViewModel model, bool newPassword)
        {
            if (!IsIdValid(model.Id)) return IdIsNotValid();

            // Remove Password from ModelState if it's not meant to change.
            if (!newPassword) ModelState.Remove(nameof(model.Password));

            if (!ModelState.IsValid)
                return await ModelStateInvalid(model);

            try
            {
                // -- Update whatever's been changed,
                // throw Exception if anything fails. --

                var user = await _dataUnit.Users.FindByIdAsync(model.Id);
                if (user == null) return UserNotFound();

                // Update UserName.
                if (user.UserName != model.UserName.Trim())
                {
                    user.UserName = model.UserName.Trim();
                }

                // Update Role.
                if (user.Role != model.Role)
                {
                    // Try setting role.
                    var setRole = await _dataUnit.Users.SetRoleAsync(user, model.Role);
                    if (setRole.Succeeded)
                    {
                        user.Role = model.Role;
                    }
                    else throw new UserRoleSetException();
                }

                // Save changes in database.
                var updateUser = await _dataUnit.Users.UpdateAsync(user);
                if (updateUser.Succeeded) { }
                else throw new UserUpdateException();

                // Update Password.
                if (newPassword)
                {
                    // Try setting new password.
                    var setNewPassword = await _dataUnit.Users.SetNewPasswordAsync(user, model.Password);
                    if (setNewPassword.Succeeded) { }
                    else throw new NewPasswordSetException();
                }

                // Success.
                return Success($"User updated: {user.UserName}, {user.Role}.");
            }
            catch (UsersControllerException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return await ViewInputAsync(model);
            }
            catch { }

            ModelState.AddModelError(string.Empty, "Could not update User.");
            return await ViewInputAsync(model);
        }


        // GET: UsersController/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (!IsIdValid(id)) return IdIsNotValid();

            var model = await _dataUnit.Users.GetUserViewModelAsync(id);
            if (model == null) return UserNotFound();

            return View(model);
        }

        // POST: UsersController/Delete/5
        [ActionName("Delete")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (!IsIdValid(id)) return IdIsNotValid();

            try
            {
                var deleteUser = await _dataUnit.Users.DeleteAsync(id);
                if (deleteUser.Succeeded)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    if (deleteUser.Errors.Any(error => error.Code == "UserNotFound"))
                    {
                        return UserNotFound();
                    }
                }
            }
            catch { }

            TempData["LayoutMessageError"] = "Could not delete User.";
            return RedirectToAction(nameof(Index));
        }

        #region private helper methods

        private IActionResult IdIsNotValid()
        {
            TempData["LayoutMessageWarning"] = "Could not find User because the given ID is not valid.";
            return RedirectToAction(nameof(Index));
        }

        private static bool IsIdValid(string id)
        {
            return Guid.TryParse(id, out Guid guid) && guid != Guid.Empty;
        }

        private async Task<IActionResult> ModelStateInvalid(UserViewModel model)
        {
            ModelState.AddModelError(
                string.Empty,
                "The input for the User was not accepted. Review the input and try again.");

            return await ViewInputAsync(model);
        }

        private IActionResult Success(string message)
        {
            TempData["LayoutMessageSuccess"] = message;
            return RedirectToAction(nameof(Index));
        }

        private IActionResult UserNotFound()
        {
            var model = new NotFoundViewModel
            {
                Title = "User not found",
                Message = "The user you're looking for was not found."
            };
            return View(nameof(NotFound), model);
        }

        private async Task<IActionResult> ViewInputAsync(UserViewModel model)
        {
            ViewBag.ComboRoles = await _dataUnit.Users.GetComboRolesAsync();

            return View(model);
        }

        #endregion private helper methods
    }
}

WiseSwitch/Views/Shared/NotFound.cshtml
@model WiseSwitch.ViewModels.NotFoundViewModel

@{
    ViewData["Title"] = "Not Found";
}

<h2 class="text-warning">@Model.Title</h2>
<p class="text-dark">@Model.Message</p>

<button onclick="javascript:history.back()" class="btn btn-link">Go back</button>

WiseSwitch/Views/Shared/_GoBackFaIcon.cshtml
<i class="fa fa-arrow-left" style="color: Highlight" href="" onclick="history.back()"></i>

WiseSwitch/Views/Shared/_HeaderPartial.cshtml
@{
    var userIdentity = User?.Identity;
    bool _isUserAuthenticated = userIdentity?.IsAuthenticated ?? false;
    bool _isUserInRoleAdmin = User?.IsInRole("Admin") ?? false;
    bool _isUserInRoleTechnician = User?.IsInRole("Technician") ?? false;
    string _userName = userIdentity?.Name ?? "error: username not found";
}

<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index"><img src="/images/WiseSwitchLogo.png" width="250" height="56"/></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            @if (_isUserAuthenticated)
            {
                <ul class="navbar-nav flex-grow-1 justify-content-evenly">
                    @if (_isUserInRoleAdmin || _isUserInRoleTechnician)
                    {
                       <!-- Manufacturers -->
                       <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Manufacturers" asp-action="Index"><i class="fa fa-microchip" style="color:#6889ae"></i> Manufacturers</a>
                       </li>
                       <!-- Brands -->
                       <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Brands" asp-action="Index"><i class="fa fa-trademark" style="color:#6889ae"></i> Brands</a>
                       </li>
                       <!-- Product Lines -->
                       <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="ProductLines" asp-action="Index"><i class="fa fa-lines-leaning" style="color:#6889ae"></i> Product Lines</a>
                       </li>
                       <!-- Product Series -->
                       <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="ProductSeries" asp-action="Index"><i class="fa fa-s" style="color:#6889ae"></i> Product Series</a>
                       </li>
                        <!-- Switch Models -->
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="SwitchModels" asp-action="Index"><i class="fa fa-sitemap" style="color:#6889ae"></i> Switch Models</a>
                        </li>
                       <!-- Firmware Versions -->
                       <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="FirmwareVersions" asp-action="Index"><i class="fa fa-terminal" style="color:#6889ae"></i> Firmware Versions</a>
                       </li>
                    }
                </ul>
                @if (_isUserInRoleAdmin)
                {
                    <ul class="navbar-nav navbar-right">
                        <!-- Users -->
                        <li class="nav-item">
                            <a class="nav-link text-dark" style="color:black" asp-controller="Users" asp-action="Index"><i class="fas fa-users-cog" style="color:#6889ae"></i> Manage Users</a>
                        </li>
                    </ul>
                }
                <ul class="navbar-nav navbar-right">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" style="color:black" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">@_userName</a>
                        <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" asp-controller="Account" asp-action="Logout">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            }
            else
            {
                <ul class="navbar-nav flex-grow-1">
                </ul>
                <ul class="navbar-nav navbar-right">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Account" asp-action="Login">Login</a>
                    </li>
                </ul>
            }
        </div>
    </div>
</nav>

WiseSwitch/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WiseSwitch</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WiseSwitch.styles.css" asp-append-version="true" />
    <link rel="icon" href="/favicon.png"/>
    <style>
        /* Hides vertical scrollbar. */
        body::-webkit-scrollbar {
            display: none;
        }
    </style>
</head>
<body>
    <header>
        @await Html.PartialAsync("_HeaderPartial")
    </header>

    <partial name="_LayoutMessage" />

    <div class="container">
        <main role="main" class="pb-3">
            <br />
            <br />
            <br />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WiseSwitch
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WiseSwitch/Views/Shared/_LayoutMessage.cshtml
@if (TempData["LayoutMessageError"] != null)
{
    <p class="mx-5 px-3 text-danger">@TempData["LayoutMessageError"]</p>
}

@if (TempData["LayoutMessageWarning"] != null)
{
    <p class="mx-5 px-3 text-warning">@TempData["LayoutMessageWarning"]</p>
}

@if (TempData["LayoutMessageSuccess"] != null)
{
    <h6 class="mx-5 px-3 text-success">@TempData["LayoutMessageSuccess"]</h6>
}

@if (TempData["LayoutMessage"] != null)
{
    <p class="mx-5 px-3">@TempData["LayoutMessage"]</p>
}